In [1]:
import pandas as pd

In [2]:
fdf = pd.read_csv('data/sgemm_product.csv')
fdf

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run1 (ms),Run2 (ms),Run3 (ms),Run4 (ms)
0,16,16,16,8,8,8,8,2,1,1,0,0,0,0,115.26,115.87,118.55,115.80
1,16,16,16,8,8,8,8,2,1,1,0,0,0,1,78.13,78.25,79.25,79.19
2,16,16,16,8,8,8,8,2,1,1,0,0,1,0,79.84,80.69,80.76,80.97
3,16,16,16,8,8,8,8,2,1,1,0,0,1,1,84.32,89.90,86.75,85.58
4,16,16,16,8,8,8,8,2,1,1,0,1,0,0,115.13,121.98,122.73,114.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,128,128,32,32,32,32,32,8,4,4,1,0,1,1,17.96,17.77,17.77,17.77
241596,128,128,32,32,32,32,32,8,4,4,1,1,0,0,36.04,36.03,36.04,36.03
241597,128,128,32,32,32,32,32,8,4,4,1,1,0,1,35.28,34.82,35.27,35.27
241598,128,128,32,32,32,32,32,8,4,4,1,1,1,0,28.43,28.49,28.44,28.45
241599,128,128,32,32,32,32,32,8,4,4,1,1,1,1,17.94,17.79,17.77,17.77

In [ ]:
# 1-2. MWG, NWG: per-matrix 2D tiling at workgroup level: {16, 32, 64, 128} (integer)
# 3. KWG: inner dimension of 2D tiling at workgroup level: {16, 32} (integer)
# 4-5. MDIMC, NDIMC: local workgroup size: {8, 16, 32} (integer)
# 6-7. MDIMA, NDIMB: local memory shape: {8, 16, 32} (integer)
# 8. KWI: kernel loop unrolling factor: {2, 8} (integer)
# 9-10. VWM, VWN: per-matrix vector widths for loading and storing: {1, 2, 4, 8} (integer)
# 11-12. STRM, STRN: enable stride for accessing off-chip memory within a single thread: {0, 1} (categorical)
# 13-14. SA, SB: per-matrix manual caching of the 2D workgroup tile: {0, 1} (categorical)

In [3]:
fdf.dtypes

MWG            int64
NWG            int64
KWG            int64
MDIMC          int64
NDIMC          int64
MDIMA          int64
NDIMB          int64
KWI            int64
VWM            int64
VWN            int64
STRM           int64
STRN           int64
SA             int64
SB             int64
Run1 (ms)    float64
Run2 (ms)    float64
Run3 (ms)    float64
Run4 (ms)    float64
dtype: object

In [4]:
fdf.describe()

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run1 (ms),Run2 (ms),Run3 (ms),Run4 (ms)
count,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000,241600.000000
mean,80.415364,80.415364,25.513113,13.935894,13.935894,17.371126,17.371126,5.000000,2.448609,2.448609,0.500000,0.500000,0.500000,0.500000,217.647852,217.579536,217.532756,217.527669
std,42.469220,42.469220,7.855619,7.873662,7.873662,9.389418,9.389418,3.000006,1.953759,1.953759,0.500001,0.500001,0.500001,0.500001,369.012422,368.677309,368.655118,368.677413
min,16.000000,16.000000,16.000000,8.000000,8.000000,8.000000,8.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,13.290000,13.250000,13.360000,13.370000
25%,32.000000,32.000000,16.000000,8.000000,8.000000,8.000000,8.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,40.660000,40.710000,40.660000,40.640000
50%,64.000000,64.000000,32.000000,8.000000,8.000000,16.000000,16.000000,5.000000,2.000000,2.000000,0.500000,0.500000,0.500000,0.500000,69.825000,69.930000,69.790000,69.820000
75%,128.000000,128.000000,32.000000,16.000000,16.000000,32.000000,32.000000,8.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,228.530000,228.310000,228.320000,228.320000
max,128.000000,128.000000,32.000000,32.000000,32.000000,32.000000,32.000000,8.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,3339.630000,3375.420000,3397.080000,3361.710000

In [6]:
fdf.isna().sum()

MWG          0
NWG          0
KWG          0
MDIMC        0
NDIMC        0
MDIMA        0
NDIMB        0
KWI          0
VWM          0
VWN          0
STRM         0
STRN         0
SA           0
SB           0
Run1 (ms)    0
Run2 (ms)    0
Run3 (ms)    0
Run4 (ms)    0
dtype: int64

In [8]:
fdf['Time'] = (fdf['Run1 (ms)'] + fdf['Run2 (ms)'] + fdf['Run3 (ms)'] + fdf['Run4 (ms)']) / 4
fdf

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run1 (ms),Run2 (ms),Run3 (ms),Run4 (ms),Time
0,16,16,16,8,8,8,8,2,1,1,0,0,0,0,115.26,115.87,118.55,115.80,116.3700
1,16,16,16,8,8,8,8,2,1,1,0,0,0,1,78.13,78.25,79.25,79.19,78.7050
2,16,16,16,8,8,8,8,2,1,1,0,0,1,0,79.84,80.69,80.76,80.97,80.5650
3,16,16,16,8,8,8,8,2,1,1,0,0,1,1,84.32,89.90,86.75,85.58,86.6375
4,16,16,16,8,8,8,8,2,1,1,0,1,0,0,115.13,121.98,122.73,114.81,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,128,128,32,32,32,32,32,8,4,4,1,0,1,1,17.96,17.77,17.77,17.77,17.8175
241596,128,128,32,32,32,32,32,8,4,4,1,1,0,0,36.04,36.03,36.04,36.03,36.0350
241597,128,128,32,32,32,32,32,8,4,4,1,1,0,1,35.28,34.82,35.27,35.27,35.1600
241598,128,128,32,32,32,32,32,8,4,4,1,1,1,0,28.43,28.49,28.44,28.45,28.4525
241599,128,128,32,32,32,32,32,8,4,4,1,1,1,1,17.94,17.79,17.77,17.77,17.8175

In [10]:
fdf.drop_duplicates(inplace=True)
fdf

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run1 (ms),Run2 (ms),Run3 (ms),Run4 (ms),Time
0,16,16,16,8,8,8,8,2,1,1,0,0,0,0,115.26,115.87,118.55,115.80,116.3700
1,16,16,16,8,8,8,8,2,1,1,0,0,0,1,78.13,78.25,79.25,79.19,78.7050
2,16,16,16,8,8,8,8,2,1,1,0,0,1,0,79.84,80.69,80.76,80.97,80.5650
3,16,16,16,8,8,8,8,2,1,1,0,0,1,1,84.32,89.90,86.75,85.58,86.6375
4,16,16,16,8,8,8,8,2,1,1,0,1,0,0,115.13,121.98,122.73,114.81,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,128,128,32,32,32,32,32,8,4,4,1,0,1,1,17.96,17.77,17.77,17.77,17.8175
241596,128,128,32,32,32,32,32,8,4,4,1,1,0,0,36.04,36.03,36.04,36.03,36.0350
241597,128,128,32,32,32,32,32,8,4,4,1,1,0,1,35.28,34.82,35.27,35.27,35.1600
241598,128,128,32,32,32,32,32,8,4,4,1,1,1,0,28.43,28.49,28.44,28.45,28.4525
241599,128,128,32,32,32,32,32,8,4,4,1,1,1,1,17.94,17.79,17.77,17.77,17.8175

In [11]:
drop_cols = ['Run1 (ms)', 'Run2 (ms)', 'Run3 (ms)', 'Run4 (ms)']
df = fdf.drop(drop_cols, axis=1)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,16,16,16,8,8,8,8,2,1,1,0,0,0,0,116.3700
1,16,16,16,8,8,8,8,2,1,1,0,0,0,1,78.7050
2,16,16,16,8,8,8,8,2,1,1,0,0,1,0,80.5650
3,16,16,16,8,8,8,8,2,1,1,0,0,1,1,86.6375
4,16,16,16,8,8,8,8,2,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,128,128,32,32,32,32,32,8,4,4,1,0,1,1,17.8175
241596,128,128,32,32,32,32,32,8,4,4,1,1,0,0,36.0350
241597,128,128,32,32,32,32,32,8,4,4,1,1,0,1,35.1600
241598,128,128,32,32,32,32,32,8,4,4,1,1,1,0,28.4525
241599,128,128,32,32,32,32,32,8,4,4,1,1,1,1,17.8175

In [12]:
replace_vals = {16:-1, 32:0, 64:1, 128:2}
df['MWG'].replace(replace_vals, inplace=True)
df['NWG'].replace(replace_vals, inplace=True)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,-1,-1,16,8,8,8,8,2,1,1,0,0,0,0,116.3700
1,-1,-1,16,8,8,8,8,2,1,1,0,0,0,1,78.7050
2,-1,-1,16,8,8,8,8,2,1,1,0,0,1,0,80.5650
3,-1,-1,16,8,8,8,8,2,1,1,0,0,1,1,86.6375
4,-1,-1,16,8,8,8,8,2,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,2,2,32,32,32,32,32,8,4,4,1,0,1,1,17.8175
241596,2,2,32,32,32,32,32,8,4,4,1,1,0,0,36.0350
241597,2,2,32,32,32,32,32,8,4,4,1,1,0,1,35.1600
241598,2,2,32,32,32,32,32,8,4,4,1,1,1,0,28.4525
241599,2,2,32,32,32,32,32,8,4,4,1,1,1,1,17.8175

In [14]:
replace_vals = {16:0, 32:1}
df['KWG'].replace(replace_vals, inplace=True)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,-1,-1,0,8,8,8,8,2,1,1,0,0,0,0,116.3700
1,-1,-1,0,8,8,8,8,2,1,1,0,0,0,1,78.7050
2,-1,-1,0,8,8,8,8,2,1,1,0,0,1,0,80.5650
3,-1,-1,0,8,8,8,8,2,1,1,0,0,1,1,86.6375
4,-1,-1,0,8,8,8,8,2,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,2,2,1,32,32,32,32,8,4,4,1,0,1,1,17.8175
241596,2,2,1,32,32,32,32,8,4,4,1,1,0,0,36.0350
241597,2,2,1,32,32,32,32,8,4,4,1,1,0,1,35.1600
241598,2,2,1,32,32,32,32,8,4,4,1,1,1,0,28.4525
241599,2,2,1,32,32,32,32,8,4,4,1,1,1,1,17.8175

In [15]:
replace_vals = {8:-1, 16:0, 32:1}
df['MDIMC'].replace(replace_vals, inplace=True)
df['NDIMC'].replace(replace_vals, inplace=True)
df['MDIMA'].replace(replace_vals, inplace=True)
df['NDIMB'].replace(replace_vals, inplace=True)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,-1,-1,0,-1,-1,-1,-1,2,1,1,0,0,0,0,116.3700
1,-1,-1,0,-1,-1,-1,-1,2,1,1,0,0,0,1,78.7050
2,-1,-1,0,-1,-1,-1,-1,2,1,1,0,0,1,0,80.5650
3,-1,-1,0,-1,-1,-1,-1,2,1,1,0,0,1,1,86.6375
4,-1,-1,0,-1,-1,-1,-1,2,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,2,2,1,1,1,1,1,8,4,4,1,0,1,1,17.8175
241596,2,2,1,1,1,1,1,8,4,4,1,1,0,0,36.0350
241597,2,2,1,1,1,1,1,8,4,4,1,1,0,1,35.1600
241598,2,2,1,1,1,1,1,8,4,4,1,1,1,0,28.4525
241599,2,2,1,1,1,1,1,8,4,4,1,1,1,1,17.8175

In [16]:
replace_vals = {2:0, 8:1}
df['KWI'].replace(replace_vals, inplace=True)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,-1,-1,0,-1,-1,-1,-1,0,1,1,0,0,0,0,116.3700
1,-1,-1,0,-1,-1,-1,-1,0,1,1,0,0,0,1,78.7050
2,-1,-1,0,-1,-1,-1,-1,0,1,1,0,0,1,0,80.5650
3,-1,-1,0,-1,-1,-1,-1,0,1,1,0,0,1,1,86.6375
4,-1,-1,0,-1,-1,-1,-1,0,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,2,2,1,1,1,1,1,1,4,4,1,0,1,1,17.8175
241596,2,2,1,1,1,1,1,1,4,4,1,1,0,0,36.0350
241597,2,2,1,1,1,1,1,1,4,4,1,1,0,1,35.1600
241598,2,2,1,1,1,1,1,1,4,4,1,1,1,0,28.4525
241599,2,2,1,1,1,1,1,1,4,4,1,1,1,1,17.8175

In [18]:
replace_vals = {1:-1, 2:0, 4:1, 8:2}
df['VWM'].replace(replace_vals, inplace=True)
df['VWN'].replace(replace_vals, inplace=True)
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Time
0,-1,-1,0,-1,-1,-1,-1,0,-1,-1,0,0,0,0,116.3700
1,-1,-1,0,-1,-1,-1,-1,0,-1,-1,0,0,0,1,78.7050
2,-1,-1,0,-1,-1,-1,-1,0,-1,-1,0,0,1,0,80.5650
3,-1,-1,0,-1,-1,-1,-1,0,-1,-1,0,0,1,1,86.6375
4,-1,-1,0,-1,-1,-1,-1,0,-1,-1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,2,2,1,1,1,1,1,1,1,1,1,0,1,1,17.8175
241596,2,2,1,1,1,1,1,1,1,1,1,1,0,0,36.0350
241597,2,2,1,1,1,1,1,1,1,1,1,1,0,1,35.1600
241598,2,2,1,1,1,1,1,1,1,1,1,1,1,0,28.4525
241599,2,2,1,1,1,1,1,1,1,1,1,1,1,1,17.8175

In [19]:
df.to_csv('data/data_cleaned.csv', index=False)